/**
 * Migrations generated by drizzle-kit, embedded as text (ADR-0016 §4). Add one line per new file in
 * `migrations/`; a test checks this list against drizzle-kit's journal.
 */
import m0000 from '../migrations/0000_init.sql?raw';
import m0001 from '../migrations/0001_customers_policies.sql?raw';
import m0002 from '../migrations/0002_kyc.sql?raw';
import m0003 from '../migrations/0003_kyc_append_only.sql?raw';

export interface Migration {
  /** Migration number; the database `schemaVersion` is the highest applied id. */
  readonly id: number;
  readonly tag: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { id: 1, tag: '0000_init', sql: m0000 },
  { id: 2, tag: '0001_customers_policies', sql: m0001 },
  { id: 3, tag: '0002_kyc', sql: m0002 },
  { id: 4, tag: '0003_kyc_append_only', sql: m0003 },
];
