/**
 * Migrations generated by drizzle-kit, embedded as text (ADR-0016 §4). Add one line per new file in
 * `migrations/`; a test checks this list against drizzle-kit's journal.
 */
import m0000 from '../migrations/0000_init.sql?raw';
import m0001 from '../migrations/0001_customers_policies.sql?raw';
import m0002 from '../migrations/0002_kyc.sql?raw';
import m0003 from '../migrations/0003_kyc_append_only.sql?raw';
import m0004 from '../migrations/0004_appointment_outcome_reviewer.sql?raw';
import m0005 from '../migrations/0005_ai_analyses.sql?raw';
import m0006 from '../migrations/0006_ai_analyses_append_only.sql?raw';

export interface Migration {
  /** Migration number; the database `schemaVersion` is the highest applied id. */
  readonly id: number;
  readonly tag: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly Migration[] = [
  { id: 1, tag: '0000_init', sql: m0000 },
  { id: 2, tag: '0001_customers_policies', sql: m0001 },
  { id: 3, tag: '0002_kyc', sql: m0002 },
  { id: 4, tag: '0003_kyc_append_only', sql: m0003 },
  { id: 5, tag: '0004_appointment_outcome_reviewer', sql: m0004 },
  { id: 6, tag: '0005_ai_analyses', sql: m0005 },
  { id: 7, tag: '0006_ai_analyses_append_only', sql: m0006 },
];

/** The highest schema version a list of migrations reaches. */
export const latestVersion = (migrations: readonly Migration[]): number =>
  Math.max(0, ...migrations.map((m) => m.id));

/** The schema version this app writes; files above it come from a newer app. */
export const LATEST_SCHEMA_VERSION = latestVersion(MIGRATIONS);
