/**
 * Migrations generated by drizzle-kit, embedded as text (ADR-0016 §4). Add one line per new file in
 * `migrations/`; a test checks this list against drizzle-kit's journal.
 */
import m0000 from '../migrations/0000_init.sql?raw';

export interface Migration {
  /** Migration number; the database `schemaVersion` is the highest applied id. */
  readonly id: number;
  readonly tag: string;
  readonly sql: string;
}

export const MIGRATIONS: readonly Migration[] = [{ id: 1, tag: '0000_init', sql: m0000 }];
