CREATE TABLE `ai_analyses` (
	`id` text PRIMARY KEY NOT NULL,
	`customer_id` text NOT NULL,
	`seq` integer NOT NULL,
	`kyc_version_id` text NOT NULL,
	`mode` text NOT NULL,
	`gate_state` text NOT NULL,
	`status` text NOT NULL,
	`provider` text NOT NULL,
	`model` text,
	`reasoning` text,
	`prompt_version` text NOT NULL,
	`attempts` integer NOT NULL,
	`input_json` text NOT NULL,
	`output_json` text,
	`raw_output` text,
	`validator_json` text NOT NULL,
	`prompt_tokens` integer,
	`completion_tokens` integer,
	`date` text NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`kyc_version_id`) REFERENCES `kyc_versions`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ai_analyses_mode_gate" CHECK(("ai_analyses"."mode" = 'analysis' AND "ai_analyses"."gate_state" = 'PAIN_POINT_ANALYSIS') OR ("ai_analyses"."mode" = 'discovery' AND "ai_analyses"."gate_state" = 'PROFILE_DISCOVERY')),
	CONSTRAINT "ai_analyses_status" CHECK("ai_analyses"."status" IN ('ACCEPTED', 'REJECTED')),
	CONSTRAINT "ai_analyses_provider" CHECK("ai_analyses"."provider" IN ('MOCK', 'OPENCODE_GO')),
	CONSTRAINT "ai_analyses_reasoning" CHECK("ai_analyses"."reasoning" IS NULL OR "ai_analyses"."reasoning" IN ('DEFAULT', 'LOW', 'MEDIUM', 'HIGH')),
	CONSTRAINT "ai_analyses_mock" CHECK("ai_analyses"."provider" <> 'MOCK' OR ("ai_analyses"."model" IS NULL AND "ai_analyses"."reasoning" IS NULL AND "ai_analyses"."prompt_tokens" IS NULL AND "ai_analyses"."completion_tokens" IS NULL)),
	CONSTRAINT "ai_analyses_model" CHECK("ai_analyses"."provider" = 'MOCK' OR ("ai_analyses"."model" IS NOT NULL AND "ai_analyses"."reasoning" IS NOT NULL)),
	CONSTRAINT "ai_analyses_attempts" CHECK("ai_analyses"."attempts" IN (1, 2)),
	CONSTRAINT "ai_analyses_tokens" CHECK(("ai_analyses"."prompt_tokens" IS NULL OR "ai_analyses"."prompt_tokens" >= 0) AND ("ai_analyses"."completion_tokens" IS NULL OR "ai_analyses"."completion_tokens" >= 0)),
	CONSTRAINT "ai_analyses_outcome" CHECK(("ai_analyses"."status" = 'ACCEPTED' AND "ai_analyses"."output_json" IS NOT NULL AND "ai_analyses"."raw_output" IS NULL) OR ("ai_analyses"."status" = 'REJECTED' AND coalesce(length("ai_analyses"."raw_output"), 0) BETWEEN 1 AND 20000))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_analyses_customer_seq` ON `ai_analyses` (`customer_id`,`seq`);